credit_str1 <- "<section> AUTHOR CONTRIBUTIONS <section> Conceptualization, I.R.D.; methodology, I.R.D., T.S., C.S.N.K., and A.D.; validation, J.S., A.B., S.E., C.A.F., I.R.D., and T.S.; formal analysis, J.S., A.B., S.E., and C.A.F.; investigation, J.S., S.E., U.B., A.B., C.A.F., H.P.D., V.D., L.K., and J.T.; resources, A.D., O.H., C.S.N.K., S.R.-S., and C.I.D.; writing – original draft, J.S., I.R.D., and T.S.; writing – review & editing, A.D., C.S.N.K., C.R., J.G., S.E., C.A.F., H.P.D., V.D., L.K., and O.H.; visualization, J.S., T.S., and I.R.D.; supervision, I.R.D. and T.S.; funding acquisition, I.R.D., T.S., A.D., <section> C.S.N.K., and C.R."

credit_str2 <- "<section> CRediT authorship contribution statement <section> Irwin Hecker: Conceptualization, Methodology, Software, Formal analysis, Investigation, Writing – original draft. <section> Tarik El Aarbaoui: Software, Methodology, Validation, Writing – review & editing. <section> Solène <section> Wallez: Software, Validation, Data curation, Writing – review & editing. <section> Astrid Juhl Andersen: Validation, Writing – review & editing. <section> José <section> Luis Ayuso-Mateos: Validation, Writing – review & editing. <section> Richard <section> Bryant: Validation, Writing – review & editing. <section> Giovanni Corrao: Validation, Writing – review & editing. <section> David McDaid: Validation, Writing – review & editing. <section> Roberto Mediavilla: Validation, Writing – review & editing. <section> Ellenor Mittendorfer-Rutz: Validation, Writing – review & editing. <section> Matteo Monzio Compagnoni: Validation, Writing – review & editing. <section> A-La Park: Validation, Writing – review & editing. <section> Antje Riepenhausen: Validation, Writing – review & editing. <section> Thomas <section> Rigotti: Validation, Writing – review & editing. <section> Katharina Seeber: Validation, Writing – review & editing. <section> Marit Sijbrandij: Validation, Writing – review & editing, Supervision, Project administration. <section> Pierre <section> Smith: Validation, Writing – review & editing. <section> Oliver Tüscher: Vali­ dation, Writing – review & editing. <section> Henrik Walter: Validation, Writing <section> – review & editing. <section> Anke Witteveen: Validation, Writing – review & editing. <section> Murielle Mary-Krause: Validation, Writing – review & editing, Supervision. <section> Maria Melchior: Conceptualization, Validation, Writing – review & editing, Supervision, Project administration, Funding <section> acquisition."

credit_str3 <- "<section> Author Contributions: Drs Kurth and Bubes had full access to all of the data in the study and take responsibility for the integrity of the data and the accuracy of the data analysis. <section> Concept and design: Kurth. <section> Acquisition, analysis, or interpretation of data: All authors. <section> Drafting of the manuscript: Kurth, Kotler, Bubes. <section> Critical revision of the manuscript for important intellectual content: Kurth, Rist, Ridker, Bubes, Buring. <section> Statistical analysis: Kurth, Kotler, Bubes. <section> Administrative, technical, or material support: Ridker, Bubes. <section> Supervision: Kurth, Ridker."

credit_str4 <- "<section> Author contributions Magda Dubois, Conceptualization, Data curation, Software, Formal analysis, Writing original draft, Writing review and editing; Johanna Habicht, Jochen Michely, Data curation, Writing review and editing; Rani Moran, Formal analysis, Writing review and editing; Ray J Dolan, Funding acquisition, Writing review and editing; Tobias U Hauser, Conceptualization, Software, Formal analysis, Supervision, Writing original draft, Writing review and editing"

credit_str5 <- "<section> Authors’ contributions. M.D.d.C.: conceptualization, formal analysis, funding acquisition, investigation, methodology, software, writing—original draft, writing—review and editing; A.W.: methodology, visualization, writing—review and editing; L.A.B.G.: methodology, visualization, writing—review and editing; P.R.: conceptualization, methodology, supervision, writing—review and editing. <section> All authors gave final approval for publication and agreed to be held accountable for the work performed therein."

credit_str6 <- "<section> Author Contributions <section> Conceptualization: Paolo Rodi, Werner Obermeyer, Mario C. Raviglione. <section> Data curation: Paolo Rodi, Mario C. Raviglione. <section> Formal analysis: Paolo Rodi. <section> Investigation: Paolo Rodi, Mario C. Raviglione. <section> Methodology: Paolo Rodi, Mario C. Raviglione. <section> Project administration: Paolo Rodi. <section> Resources: Paolo Rodi, Werner Obermeyer, Ariel Pablos-Mendez, Mario C. Raviglione. <section> Software: Paolo Rodi. <section> Supervision: Werner Obermeyer, Mario C. Raviglione. <section> Validation: Paolo Rodi, Ariel Pablos-Mendez, Mario C. Raviglione. <section> Visualization: Paolo Rodi, Andrea Gori. <section> Writing – original draft: Paolo Rodi. <section> Writing – review & editing: Paolo Rodi, Werner Obermeyer, Ariel Pablos-Mendez, Andrea Gori, Mario C. Raviglione."

credit_str7 <- "<section> Author Contributions <section> The followings are the authors\\u2019 contributions: study concepts: M.K. and U.K; study design: M.K. and U.K; data acquisition: K.K., M.K., and U.K; quality control of data and algorithms: K.K., U.G., M.K., and V.G; data analysis and interpretation: P.M., U.G., K.K., and U.K; statistical analysis: P.M., U.G., and K.K; manuscript preparation: U.G. and K.K; manuscript editing: all; manuscript review: all."

credit_str8 <- "<section> Author contribution LJM; DM; JM — conceived and designed. <section> LJM; JI; MW; OT; HW; KK; JM; NR; DM — performed research. <section> LJM; MW – analysed data. <section> LJM – wrote paper."

credit_str9 <- "<section> Author Contributions A. Staats Pires: drafting/revision of the manuscript for content, including medical writing for content; major role in the acquisition of data; study concept or design; analysis or interpretation of data. S. Krishnamurthy: major role in the acquisition of data; analysis or interpretation of data. S. Sharma: drafting/revision of the manuscript for content, including medical writing for content; major role in the acquisition of data. S. Chow: major role in the acquisition of data; analysis or interpretation of data. S. Klistorner: drafting/revision of the manuscript for content, including medical writing for content; major role in the acquisition of data. G.J. Guillemin: drafting/ revision of the manuscript for content, including medical writing for content; analysis or interpretation of data. A. <section> Klistorner: drafting/revision of the manuscript for content, including medical writing for content; major role in the acquisition of data. Y. You: drafting/revision of the manuscript for content, including medical writing for content; major role in the acquisition of data; study concept or design; analysis or interpretation of data. B. Heng: drafting/revision of the manuscript for content, including medical writing for content; major role in the acquisition of data; study concept or design; analysis or interpretation of data."

test_that("parsing of CRediT roles into keyvalue pair tables", {
  expect_equal(parse_credit_roles(credit_str1) |> nrow(), 52)
  expect_equal(parse_credit_roles(credit_str2) |> nrow(), 58)

  expect_equal(parse_credit_roles(credit_str4) |> nrow(), 20)
  expect_equal(parse_credit_roles(credit_str5) |> nrow(), 18)
  expect_equal(parse_credit_roles(credit_str6) |> nrow(), 29)
})

test_that("parsing non-CRediT roles that are given as lists", {
  expect_equal(parse_credit_roles(credit_str3) |> nrow(), 17) # not CRediT
  expect_equal(parse_credit_roles(credit_str7) |> nrow(), 22) # not CRediT
  expect_equal(parse_credit_roles(credit_str8), NA) # not CRediT, narrative
  expect_equal(parse_credit_roles(credit_str9) |> nrow(), 9)
})

