all_authors:
  - "All authors"
  - "The authors"
  - "All the authors"
  - "The author\\(s\\)"

contributed_equally:
  - "contributed equally"

criteriaship_keywords:
  - responsible
  - accountable
  - responsibility
  - authorship
  - substantial
  - direct
  - met criteria

CRediT_Roles:
  - Conceptualization
  - Data curation
  - Formal analysis
  - Funding acquisition
  - Investigation
  - Methodology
  - Project administration
  - Software
  - Resources
  - Supervision
  - Validation
  - Visualization
  - Writing
  - review
  - editing

CRediT_Roles_Variations:
  - Conceptuali(z|s)ation
  - Conceptualism
  - Data curation
  - Formal analysis
  - "Formal data analysis"
  - "Funding[^\\w]+acquisition"
  - funding
  - Investigations?
  - Methodology
  - "Project[^\\w]+administration"
  - Software
  - Resources
  - Supervision
  - Validation
  - "Visualizations?"
  - "Visualisations?"
  - "Review\\s*[^.,;:]*"
  - "Edit\\s*[^.,;:]*"
  - "Writing\\s*[^.,;:]*"
  - "Original\\s*[^.,;:]*"
Modifiers:
  - lead
  - supporting
  - equal

Verbs_keywords:
  - acted
  - acquired
  - conceived
  - conducted
  - developed
  - designed
  - drafted
  - established
  - "had taken"
  - helped
  - implemented
  - initiated
  - looked
  - participated
  - planned
  - prepared
  - proposed
  - responsible
  - suggested
  - supervised
  - "was the"
  - wrote
  - written
  - conceptualized
  - involved
  - contributed
  - led
  - collected
  - completed

Roles:
  - Conceptualization
  - Data curation
  - Formal analysis
  - Funding acquisition
  - Investigation
  - Methodology
  - Project administration
  - Software
  - Resources
  - Supervision
  - Validation
  - Visualization
  - Writing
  - review
  - editing
Narrative:
  - Conceptuali(z|s)ation
  - Conceptualism
  - "Data curation"
  - "Formal analysis"
  - "Formal data analysis"
  - "Funding[^\\w]+acquisition"
  - funding
  - Investigations?
  - Methodology
  - "Project[^\\w]+administration"
  - Software
  - Resources
  - Supervision
  - Validation
  - Visualizations?
  - Visualisations?
  - "Edit\\s*[^.,;:]*"
  - "Writing\\s*[^.,;:]*"


filter_keywords:
  - preparation
  - Figures
  - design
  - coding
  - "data\\w*"
  - "study\\w*"
  - tests
  - funding
  - "experiment\\w*"
  - writing
  - editing
  - analyses
  - "concept\\w*"
  - modelling
  - harmonisation
  - Suggestions
  - analysis
  - project
